### ISSUE TITLE
LICENSE.txt should not be installed into the root of the prefix

### ISSUE THREAD

**Issue by kkofler** [PabloCastellano/libcnml#14]
Your `setup.py` contains the following code at line 31:

``` python
data_files=[('', ['LICENSE.txt'])],
```

This installs the `LICENSE.txt` file into the root directory of the installation prefix. But in GNU/Linux distribution packages, the installation prefix is typically `/usr`, so the file ends up at `/usr/LICENSE.txt`, which is not a path compliant with the FHS (Filesystem Hierarchy Standard), and would also cause file conflicts if everyone tried to install their license files there.

Please either install the license to an appropriate directory (i.e. somewhere under `$prefix/share`), or simply do not install it at all. Most distributions will just install it to their own favorite directory anyway: e.g., Debian does not install copies of the GPL in individual packages at all (referencing the system copy instead), Fedora has a `%license` RPM macro which automatically installs the license to `/usr/share/licenses/$packagename`, so in both cases, an automatic installation of `LICENSE.txt` by the upstream build system is neither needed nor wanted.

**Comment by nemesifier** [comment]
@PabloCastellano, @Germano0 noticed this while packaging the dependencies of https://github.com/interop-dev/django-netjsongraph for Fedora, we are working to make it easy to install mesh apps on popular linux distros.
