### ISSUE TITLE
shabang

### ISSUE THREAD

**Issue by Germano0** [PabloCastellano/libcnml#17]
https://github.com/PabloCastellano/libcnml/blob/master/libcnml/libcnml.py
contains shabang even if the file is not an executable file. If the file is not an executable file, please remove the shabang

**Comment by PabloCastellano** [comment]
Done. thanks!

**Comment by Germano0** [comment]
I started the procedure to include python-libcnml in Fedora's repositories. If you can provide a new minor release, I can avoid making a patch file to remove the shabang from lastest libcnml stable release.
Thank you!

**Comment by PabloCastellano** [comment]
0.9.4 released!

**Comment by Germano0** [comment]
Thank you very much
