### ISSUE TITLE
Mainipv4 device attributes causes som error

### ISSUE THREAD

**Issue by emmdim** [PabloCastellano/libcnml#20]
@PabloCastellano 
Executing versions of libcnml above this [commit](https://github.com/PabloCastellano/libcnml/commit/aa62385bfd9c8914b234b7163025226ef7914d0b) against the CNML of zone [2742](https://guifi.net/es/guifi/cnml/2742/detail) gives me the following error:

2742:8:0:ERROR:VALID:DTD_MISSING_ATTRIBUTE: Element device does not carry attribute mainipv4

(Btw if this doesn't work cannto check the other stuff :-P )

**Comment by PabloCastellano** [comment]
I have just downloaded that zone and validation goes well.
Maybe you are using an older version of the zone when it didn't include that attribute?

**Comment by emmdim** [comment]
Sorry for the confusion. My mistake. I was using the the test.guifi.net which in some weird way has the old cnml version.
