### ISSUE TITLE
Release a new pypi version with mainipv4 support

### ISSUE THREAD

**Issue by itorres** [PabloCastellano/libcnml#22]
The current release (0.9.4) does not include the `mainipv4` addition from https://github.com/PabloCastellano/libcnml/commit/aa62385bfd9c8914b234b7163025226ef7914d0b so current guifi.net CNML files do not validate with lxml.

> /root/.local/guifibages/cnml_cache/3671.detail.cnml:2374:0:ERROR:VALID:DTD_UNKNOWN_ATTRIBUTE: No declaration for attribute mainipv4 of element device

**Comment by PabloCastellano** [comment]
Released v0.9.5
