### ISSUE TITLE
Missing reference from CNMLNode to the parent CNMLZone

### ISSUE THREAD

**Issue by emmdim** [PabloCastellano/libcnml#7]

**Comment by emmdim** [comment]
The CNMLZone attribute for the node is not actually part of the CNML definition. The proposal was made to facilitate the users. Nevertheless, I started implementing based on the current version of the code but with the new differtiation for "detailed" cnml it seems to be more complicated than in the original version.  Maybe we should drop it.

**Comment by PabloCastellano** [comment]
Fixed
